/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zeus.jPanels;

import zeus.conexaoDB.ConexaoDB;
import zeus.classes.Pessoa;
import java.sql.ResultSet;
import javax.swing.*;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import zeus.classes.Admin;
import zeus.classes.Aluno;
import zeus.classes.Controler;
import zeus.classes.Pessoa;
import zeus.classes.Professor;
import zeus.conexaoDB.ConexaoDB;

/**
 *
 * @author Adriel Rosa
 */
public class PPanel extends javax.swing.JFrame {

    /**
     * Creates new form FrameZeusPanelManager
     */
    private String usuario = null;
    private int nivel_de_acesso = 0;
    private ConexaoDB conexao = new ConexaoDB();
    
    public PPanel(Aluno aluno) {
        initComponents();
        readJtable();
        usuarioLogado.setText(aluno.getNome());
        usuario = aluno.getUsuario();
        nivel_de_acesso = aluno.getNivel_de_acesso();
        cadastrarNovoUsuario.setEnabled(false);
        
    }
    public PPanel(Professor professor) {
        initComponents();
        readJtable();
        usuarioLogado.setText(professor.getNome());
        usuario = professor.getUsuario();
        nivel_de_acesso = professor.getNivel_de_acesso();
        cadastrarNovoUsuario.setEnabled(false);
        
    }
    public PPanel(Admin admin) {
        initComponents();
        readJtable();
        usuarioLogado.setText(admin.getNome());
        usuario = admin.getUsuario();
        nivel_de_acesso = admin.getNivel_de_acesso();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        consultarUsuario = new javax.swing.JButton();
        atualizarTabela = new javax.swing.JButton();
        cadastrarNovoUsuario = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usuarioLogado = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZEUS - People Manager Panel");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("imagens/iconzeus.png")).getImage());
        setMinimumSize(new java.awt.Dimension(930, 720));
        setPreferredSize(new java.awt.Dimension(930, 720));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jPanel2.setBackground(new java.awt.Color(135, 159, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bem vindo ao painel!");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "NOME", "TIPO USER", "DATA NASCIMENTO", "E-MAIL", "TELEFONE"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(41, 84, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(171, 188, 255));

        consultarUsuario.setBackground(new java.awt.Color(23, 23, 255));
        consultarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        consultarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        consultarUsuario.setText("Consultar Usuário");
        consultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuarioActionPerformed(evt);
            }
        });

        atualizarTabela.setBackground(new java.awt.Color(23, 23, 255));
        atualizarTabela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        atualizarTabela.setText("Atualizar Tabela");
        atualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTabelaActionPerformed(evt);
            }
        });

        cadastrarNovoUsuario.setBackground(new java.awt.Color(23, 23, 255));
        cadastrarNovoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarNovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarNovoUsuario.setText("Cadastrar Novo Usuário");
        cadastrarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoUsuarioActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(171, 188, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Sair");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário conectado:");

        usuarioLogado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioLogado.setText("Exemplo de usuario da silva");

        btnPerfil.setBackground(new java.awt.Color(171, 188, 255));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(null);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("|");

        jButton1.setBackground(new java.awt.Color(171, 188, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Sobre");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(btnPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usuarioLogado))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(consultarUsuario)
                            .addGap(18, 18, 18)
                            .addComponent(atualizarTabela)
                            .addGap(18, 18, 18)
                            .addComponent(cadastrarNovoUsuario)))
                    .addContainerGap(241, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPerfil)
                    .addComponent(jButton6)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(usuarioLogado))
                    .addGap(23, 23, 23)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastrarNovoUsuario)
                        .addComponent(atualizarTabela)
                        .addComponent(consultarUsuario))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(919, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PLogin p_login = new PLogin();
        this.dispose();
        p_login.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cadastrarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoUsuarioActionPerformed
        PTipoCadastro painel_cadastro = new PTipoCadastro();
        painel_cadastro.setVisible(true);
    }//GEN-LAST:event_cadastrarNovoUsuarioActionPerformed

    private void atualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarTabelaActionPerformed
        limparTabela();
        readJtable();
    }//GEN-LAST:event_atualizarTabelaActionPerformed

    private void consultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuarioActionPerformed
        int nivel_acesso = conexao.validarTipoPessoa(usuario);
        if (nivel_acesso == 1){
            Aluno aluno = conexao.extrairAluno(usuario);
            new PPesquUsuario(aluno).setVisible(true);
        } else if (nivel_acesso == 2){
            Professor professor = conexao.extrairProfessor(usuario);
            new PPesquUsuario(professor).setVisible(true);
        } else if (nivel_acesso == 3){
            Admin admin = conexao.extrairAdmin(usuario);
            new PPesquUsuario(admin).setVisible(true);
        }
    }//GEN-LAST:event_consultarUsuarioActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        if (nivel_de_acesso == 1){
            Aluno aluno = conexao.extrairAluno(usuario);
            
            PPerfilAluno pAluno = new PPerfilAluno(usuario);
            pAluno.setVisible(true);
        } else if (nivel_de_acesso == 2){
            Professor professor = conexao.extrairProfessor(usuario);
            PPerfilProfessor pProfessor = new PPerfilProfessor(usuario);
            pProfessor.setVisible(true);
        } else if (nivel_de_acesso == 3){
            Admin admin = conexao.extrairAdmin(usuario);
            PPerfilAdmin pAdmin = new PPerfilAdmin(usuario);
            pAdmin.setVisible(true);
        }
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PAbout pAbout = new PAbout();
        pAbout.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public String tipoUsuario(int nivel_de_acesso){
        if (nivel_de_acesso == 1){
            return "Aluno";
        } else if (nivel_de_acesso == 2){
            return "Professor";
        } else if (nivel_de_acesso == 3){
            return "Admin";
        }
        return "Desconhecido";
    }
    public void readJtable(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        Controler plist_result = new Controler();
        
        for (Pessoa p: plist_result.read()){
            modelo.addRow(new Object[]{
                p.getUsuario(),
                p.getNome(),
                tipoUsuario(p.getNivel_de_acesso()),
                p.getData_nascimento(),
                p.getEmail(),
                p.getTelefone()
            });
        }        
    }
    private void limparTabela() { 
        DefaultTableModel dm = null;
        while (jTable1.getRowCount () > 0) { 
            dm = (DefaultTableModel) jTable1.getModel ();
            dm.getDataVector ().removeAllElements ();
        }
    }
    private void carregarPerfil(){
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarTabela;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton cadastrarNovoUsuario;
    private javax.swing.JButton consultarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel usuarioLogado;
    // End of variables declaration//GEN-END:variables
}
