/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zeus.jPanels;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriel Rosa
 */
public class PPhotoPerfil extends javax.swing.JFrame  {

    private static final long serialVersionUID = 1L;

    private JPanel painel = new JPanel();
    private JButton btnCarregar = new JButton("Carregar");
    private JFileChooser fileChooser = new JFileChooser();
    private File diretorioImagens = new File("zeus.jPanels.imagens");
    private String usuario = null;
    private String nome_usuario = null;
    
    /**
     * Creates new form PPhotoPerfil
     */
    public PPhotoPerfil(String usuario_entrada, String nome_entrada) {
        usuario = usuario_entrada;
        nome_usuario = nome_entrada;
        initComponents();
        carregarDadosUsuario(usuario, nome_usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        nomeUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fotoPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Foto de Perfil");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("imagens/iconzeus.png")).getImage());
        setMinimumSize(new java.awt.Dimension(440, 410));
        setPreferredSize(new java.awt.Dimension(440, 410));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jPanel2.setBackground(new java.awt.Color(135, 159, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Foto de Usuario");

        btnVoltar.setBackground(new java.awt.Color(135, 159, 255));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus/images/btn-voltar.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        nomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeUsuario.setText("Usuário da silva");

        jButton1.setBackground(new java.awt.Color(23, 23, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Abrir/Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(23, 23, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Apagar Foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(135, 159, 255));

        fotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus/images/userDefault.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoPerfil)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fotoPerfil)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(111, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 352));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String arquivo_origem = null;
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".jpg") || f.getName().toLowerCase().endsWith(".jpeg")
                        || f.getName().toLowerCase().endsWith(".png") || f.isDirectory();
            }

            public String getDescription() {
                return "Imagens (*.jpg, *.jpeg, *.png)";
            }
        });

        int retorno = fileChooser.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            File arquivoSelecionado = fileChooser.getSelectedFile();
            //System.out.println(arquivoSelecionado.getName());
            //System.out.println(diretorioImagens.getAbsolutePath());

            try {
                FileInputStream fis = new FileInputStream(arquivoSelecionado);
                byte[] buffer = new byte[fis.available()];
                fis.read(buffer);
                fis.close();

                if (!diretorioImagens.exists()) {
                    diretorioImagens.mkdirs();
                }
                
                String extensaoImagem = arquivoSelecionado.getName().substring(arquivoSelecionado.getName().lastIndexOf(".") + 1);
                //System.out.println(extensaoImagem);
                //System.out.println(extensaoImagem.getClass().getName());
                extensaoImagem = "png";
                
                File arquivoDestino = new File(diretorioImagens.getAbsolutePath() + File.separator + usuario + "." + extensaoImagem);
                arquivo_origem = arquivoDestino.getAbsolutePath();
                FileOutputStream fos = new FileOutputStream(arquivoDestino);
                fos.write(buffer);
                fos.close();

                //ImageIcon icone = new ImageIcon(getClass().getResource(String.format("%s", arquivoDestino.getAbsolutePath()))); 
                //Desktop.getDesktop().open(arquivoDestino);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        String arquivo_destino = diretorioImagens.getAbsolutePath();
        String imagem_final = null;
        try {
            imagem_final = reduzirImagem(arquivo_origem, arquivo_destino);
        } catch (IOException ex) {
            System.out.println("Erro ao reduzir imagem: "+ex.getMessage());
        }
        setarImagem(usuario);
        JOptionPane.showMessageDialog(null, "A atualização entrarar em vigor após a proxima reinicialização do sistema!", "Atualizado com sucesso!", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String diretorioImg = diretorioImagens.getAbsolutePath();
        String testenovopath = diretorioImg+usuario+".png";
        File file = new File(testenovopath);
        if (file.delete()) {
            System.out.println("Arquivo excluído com sucesso!");
        } else {
            System.out.println("Falha ao excluir o arquivo.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    private String reduzirImagem(String pathFileOrigim, String pathFileSave) throws IOException{
        String caminhoImagem = pathFileOrigim; //"caminho/para/imagem";
        String extensaoImagem = caminhoImagem.substring(caminhoImagem.lastIndexOf(".") + 1);
        File imagem = new File(caminhoImagem);
        BufferedImage imagemOriginal = ImageIO.read(imagem);
        
        String nomeDaImagem = imagem.getName();

        int novaLargura = 150;
        int novaAltura = 150;

        Image novaImagem = imagemOriginal.getScaledInstance(novaLargura, novaAltura, Image.SCALE_SMOOTH);
        BufferedImage novaImagemBuffered = new BufferedImage(novaLargura, novaAltura, BufferedImage.TYPE_INT_RGB);
        novaImagemBuffered.getGraphics().drawImage(novaImagem, 0, 0, null);
        
        System.out.println(nomeDaImagem);
        String caminhoNovaImagem = pathFileSave + nomeDaImagem; //+ "." + extensaoImagem;
        ImageIO.write(novaImagemBuffered, extensaoImagem, new File(caminhoNovaImagem));
        
        return caminhoNovaImagem;
    }
    private void setarImagem (String usuario){
        String diretorioImg = diretorioImagens.getAbsolutePath();
        String testenovopath = diretorioImg+usuario+".png";
        //System.out.println(testenovopath);
        try {
            ImageIcon icone = new ImageIcon(testenovopath);
            fotoPerfil.setIcon(icone);
        } catch (Exception ex) {
            setarImagemDefault();
            System.out.println("Erro ao setar imagem: "+String.valueOf(ex));
        }
    }
    private void setarImagemDefault (){
        try {
            ImageIcon icone = new ImageIcon(getClass().getResource("imagens/userDefault.png"));
            fotoPerfil.setIcon(icone);
        } catch (Exception ex) {
            System.out.println("Erro ao setar imagem default: "+String.valueOf(ex));
        }
    }
    private void carregarDadosUsuario(String usuario, String nome){
        try {
            setarImagem(usuario);
            nomeUsuario.setText(nome);
            
        } catch (Exception ex) {
            System.out.println("Erro ao carregar dados de aluno: "+String.valueOf(ex));
        }
        fotoPerfil.repaint();
        fotoPerfil.revalidate();
    }
    private void atualizar(){
        this.dispose();
        new PPhotoPerfil(usuario, nome_usuario).setVisible(true);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel fotoPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nomeUsuario;
    // End of variables declaration//GEN-END:variables
}
