/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zeus.jPanels;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import com.mysql.cj.protocol.Resultset;
import javax.swing.JOptionPane;
import zeus.conexaoDB.ConexaoDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adriel Rosa
 */
public class PRecsenha extends javax.swing.JFrame {

    /**
     * Creates new form PRecsenha
     */
    public PRecsenha() {
        initComponents();
    }
    private String usuario_a_validar = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputUserValidacao = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        comboboxPRecSenha = new javax.swing.JComboBox<>();
        inputRRecSenha = new javax.swing.JTextField();
        btnAlterarSenha = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        novaSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ZEUS - Recuperação de senha");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("imagens/iconzeus.png")).getImage());
        setMinimumSize(new java.awt.Dimension(395, 474));
        setPreferredSize(new java.awt.Dimension(386, 474));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(386, 386));
        jPanel1.setPreferredSize(new java.awt.Dimension(386, 386));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(135, 159, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Recuperação de senha");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Digite o usuario ou o e-mail cadastrado:");

        inputUserValidacao.setBackground(new java.awt.Color(188, 201, 255));
        inputUserValidacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputUserValidacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserValidacaoActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(23, 23, 255));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Questionário de recuperação:");

        comboboxPRecSenha.setBackground(new java.awt.Color(188, 201, 255));
        comboboxPRecSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboboxPRecSenha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Onde seus pais se conhecera?", "Qual é o nome do seu melhor amigo de infância?", "Em que cidade você nasceu?", "Qual é o nome do seu primeiro professor?", "Qual é o nome do seu primeiro amor?", "Em que ano você se formou no ensino médio?", "Qual é o nome da sua avó materna?", "Qual é a sua comida favorita?", "Qual é o nome do seu primeiro animal de estimação?" }));
        comboboxPRecSenha.setEnabled(false);

        inputRRecSenha.setBackground(new java.awt.Color(188, 201, 255));
        inputRRecSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputRRecSenha.setEnabled(false);

        btnAlterarSenha.setBackground(new java.awt.Color(23, 23, 255));
        btnAlterarSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.setToolTipText("");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(135, 159, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus/images/btn-voltar.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        novaSenha.setBackground(new java.awt.Color(188, 201, 255));
        novaSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        novaSenha.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Insira a nova senha:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnVoltar)
                .addGap(53, 53, 53)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(inputUserValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnConfirmar))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(comboboxPRecSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(inputRRecSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(inputUserValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnConfirmar)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comboboxPRecSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(inputRRecSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarSenha)
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 372, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String inputUserRecSenha = inputUserValidacao.getText();
        ConexaoDB conect_class = new ConexaoDB();
        Statement stmt = conect_class.iniciarConexao();
        try {
            ResultSet retorno_banco = stmt.executeQuery(
                    String.format("SELECT usuario, pgt_rec_senha FROM pessoa WHERE usuario = '%s';", inputUserRecSenha)
            );
            boolean laco = false;
            while (retorno_banco.next()){
                laco = true;
                if (!"".equals(retorno_banco.getString("usuario"))){
                    JOptionPane.showMessageDialog(null, "Recuperação de senha liberada!\nResponda o questionario.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                    comboboxPRecSenha.enable(true);
                    inputRRecSenha.enable(true);
                    btnAlterarSenha.enable(true);
                    novaSenha.enable(true);
                    //System.out.println("Recuperação de senha liberada!");
                    comboboxPRecSenha.setSelectedItem(String.format("%s", retorno_banco.getString("pgt_rec_senha")));
                    usuario_a_validar = inputUserRecSenha;
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario ou e-mail não encontrado!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (laco == false){
                JOptionPane.showMessageDialog(null, "Usuario ou e-mail não encontrado!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(String.format("Erro ao iniciar conexão: %s", ex));
        } 
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new PLogin().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void inputUserValidacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserValidacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserValidacaoActionPerformed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        if (usuario_a_validar != null){
            String resp_rec = inputRRecSenha.getText();
            String nova_senha = novaSenha.getText();
            ConexaoDB conect_class = new ConexaoDB();
            Statement stmt = null;
            Statement n_stmt = null;
            try {
                stmt = conect_class.iniciarConexao();
                ResultSet retorno_pregunta = stmt.executeQuery(String.format("SELECT resp_rec_senha FROM pessoa WHERE usuario = '%s' ;", usuario_a_validar));
                String resposta = conect_class.extrairString(retorno_pregunta, "resp_rec_senha");
                if (resp_rec.equals(resposta)){
                    n_stmt = conect_class.iniciarConexao();
                    String query = String.format("UPDATE pessoa SET senha = '%s' WHERE usuario = '%s';", nova_senha, usuario_a_validar);
                    n_stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Senha alterada com sucesso!", "Alteração de senha.", JOptionPane.INFORMATION_MESSAGE);
                    new PLogin().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Resposta Incorreta!", "Alteração de senha.", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException ex) {
                System.out.println(String.format("Erro ao tentar redefinir a senha: ", ex));
            } 
        }
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboboxPRecSenha;
    private javax.swing.JTextField inputRRecSenha;
    private javax.swing.JTextField inputUserValidacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField novaSenha;
    // End of variables declaration//GEN-END:variables
}
